---
build_from:
  aarch64: ghcr.io/hassio-addons/base:latest
  amd64: ghcr.io/hassio-addons/base:latest
  armv7: ghcr.io/hassio-addons/base:latest
codenotary:
  base_image: notary@home-assistant.io
  signer: andrewjswan@addons.community
